AWSTemplateFormatVersion: '2010-09-09'
Description: Basic CloudFormation Template to Create an EC2 Instance

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080 
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup
      ImageId: ami-0e2c8caa4b6378d8c  

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
